version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/documentDataDatabase
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pR1SmKfeHsU3
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=documentDataDatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pR1SmKfeHsU3
    ports:
      - "5432:5432"
    volumes:
      - document-data:/var/lib/postgresql/data

volumes:
  document-data:
